### PR TITLE
Use the latest version of graphiql-explorer

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@wawhal Most of the feedback from you fixed (see https://github.com/OneGraph/onegraph-changelog/issues/45). :wink:

**Comment by FluorescentHallucinogen** [comment]
Should `package-lock.json` be updated (regenerated) too?

**Comment by wawhal** [comment]
@FluorescentHallucinogen apologies for the late reply. Could you run `npm install` so that `package-lock` gets generated?

**Comment by FluorescentHallucinogen** [comment]
@wawhal I've changed `"graphiql-explorer": "^0.4.4"` to `"graphiql-explorer": "^0.5.1"` and no need to update the `package-lock.json`. I've removed the `node_modules` folder, ran `npm install`, and `package-lock.json` hasn't changed (byte identical). I also checked the version in `node_modules\graphiql-explorer` folder. And it's `0.5.1`, not `0.4.4` :+1: So this pull-request is ready to merge. :wink:

**Pull request merged**
